# Generated by Django 3.1.7 on 2022-02-24 05:37

from django.db import migrations, models
import django.utils.timezone
import ticket.ticket_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=ticket.ticket_number.ticket_number_generator, editable=False, max_length=25)),
                ('title', models.CharField(max_length=150, verbose_name='Bug Title')),
                ('description', models.TextField(max_length=500, verbose_name='Bug Description')),
                ('ticket_status', models.CharField(blank=True, choices=[('SUB', 'SUBMITTED'), ('REJ', 'REJECTED'), ('A&U', 'APPROVED AND UNASSIGNED'), ('A&A', 'APPROVED AND ASSIGNED'), ('POS', 'POSTPONED'), ('RES', 'RESOLVED'), ('CLO', 'CLOSED'), ('DUP', 'DUPLICATE')], default='SUB', max_length=3, null=True)),
                ('severity_level', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MIN', 'MINOR'), ('MAJ', 'MAJOR'), ('CRI', 'CRITICAL')], max_length=3, null=True)),
                ('priority_level', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MED', 'MEDIUM'), ('HIG', 'HIGH')], max_length=3, null=True)),
                ('public_view', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('screenshot', models.ImageField(blank=True, default=None, null=True, upload_to='ticket/ticket-screenshots/')),
            ],
        ),
    ]
