# Generated by Django 3.1.7 on 2022-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='Product Description', max_length=500)),
                ('date_of_launch', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='product/product-logo/')),
            ],
        ),
    ]
