# Generated by Django 3.1.7 on 2022-02-24 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='administrator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
